default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  database: depot_test

production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
