default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: depot_test
