default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: depot
  username: postgres

  # The password associated with the PostgreSQL role (username).
  password: pavel

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 5432

test:
  <<: *default
  database: depot_test

production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    encoding: unicode
