default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>

test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>

  # For Solid Queue
  queue:
    <<: *default
    database: <%= ENV["PGDATABASE"] %>_queue

  # For Solid Cable
  cable:
    <<: *default
    database: <%= ENV["PGDATABASE"] %>_cable
